# Generated by Django 4.2.2 on 2023-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_year', models.CharField(blank=True, max_length=255)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('insight', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=255)),
                ('start_year', models.CharField(blank=True, max_length=255)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
