# Generated by Django 4.2.2 on 2023-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='end_year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='impact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='insight',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='pestle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='sector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='start_year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
