# Generated by Django 4.2.2 on 2023-12-13 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djid_app', '0002_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='impact',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='start_year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
